# Copyright (c) 2018 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
  redis:
    image: "redis:alpine"
