#
# Copyright (c) 2018 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: batch/v1
kind: Job
metadata:
  name: process-item-$ITEM
  labels:
    jobgroup: jobtest
spec:
  template:
    metadata:
      name: jobtest
      labels:
        jobgroup: jobtest
    spec:
      runtimeClassName: kata
      containers:
      - name: test
        image: busybox
        command: ["tail", "-f", "/dev/null"]
      restartPolicy: Never
