#
# Copyright (c) 2018 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Pod
metadata:
  name: besteffort-test
spec:
  runtimeClassName: kata
  containers:
  - name: qos-besteffort
    image: busybox
    command: ["/bin/sh", "-c", "tail -f /dev/null"]
