#
# Copyright (c) 2018 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Pod
metadata:
  name: burstable-test
spec:
  runtimeClassName: kata
  containers:
  - name: qos-burstable
    image: busybox
    command: ["/bin/sh", "-c", "tail -f /dev/null"]
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
