#
# Copyright (c) 2018 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  runtimeClassName: kata
  containers:
    - name: test-container
      image: busybox
      command: ["/bin/sh", "-c", "tail -f /dev/null"]
      volumeMounts:
          # name must match the volume name below
          - name: secret-volume
            mountPath: /tmp/secret-volume
  # The secret data is exposed to Containers in the Pod through a Volume.
  volumes:
    - name: secret-volume
      secret:
        secretName: test-secret
