#
# Copyright (c) 2018 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Pod
metadata:
  name: secret-envars-test-pod
spec:
  runtimeClassName: kata
  containers:
  - name: envars-test-container
    image: busybox
    command: ["/bin/sh", "-c", "tail -f /dev/null"]
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: test-secret
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: test-secret
          key: password
