#
# Copyright (c) 2018 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
kind: Pod
apiVersion: v1
metadata:
  name: pv-pod
spec:
  runtimeClassName: kata
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
       claimName: pv-claim
  containers:
    - name: pv-container
      image: busybox
      ports:
      command:
        - sleep
        - "120"
      volumeMounts:
        - mountPath: "/mnt/"
          name: pv-storage
