#
# Copyright (c) 2019 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: ReplicationController
metadata:
  name: replicationtest
spec:
  replicas: 1
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      runtimeClassName: kata
      containers:
      - name: nginxtest
        image: "${nginx_version}"
        ports:
        - containerPort: 80
